# Generated by Django 3.0.11 on 2021-02-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('method', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('train_file_x', models.FileField(max_length=300, upload_to='upload_data')),
                ('train_file_y', models.FileField(max_length=300, upload_to='upload_data')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trained_model', models.FileField(max_length=300, upload_to='')),
                ('mean_test_score', models.FloatField()),
                ('model_information', models.TextField(max_length=300)),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('model_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic_app.ModelSetting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(fields=('model_setting',), name='defining_fields_MLModel'),
        ),
    ]
